---
title: "epl"
format: html
editor: visual
---

```{r}
library(worldfootballR)
```

```{r}
library(tidyverse)
```



```{r}
get_current_matchweek <- function() {
  url <- ("https://www.transfermarkt.com/premier-league/startseite/wettbewerb/GB1")

html <- read_html(url)


  text <- html_nodes(html, ".fl") |> 
  html_children() |> 
  html_attr("href")
  
  text2 <- stringr::str_remove(text, "/premier-league/spieltag/wettbewerb/GB1/spieltag/")

text2 |> str_extract("^.{2}") |> as.numeric() |> mean()
  
}
```


```{r}
df_total = data.frame()
for (i in 1:get_current_matchweek()) {
  print(paste("Getting Matchweek:", i))
  data <- tm_matchday_table(country_name="England", start_year="2022", matchday=i)
  df_total <- rbind(df_total, data)
}

df_total <- df_total |> 
   group_by(squad) |> distinct(matchday, .keep_all = TRUE) |> ungroup()

# https://stackoverflow.com/questions/29402528/append-data-frames-together-in-a-for-loop
```

```{r}
df_total
```

```{r}
current_standings <- tm_matchday_table("England", "2022", get_current_matchweek()) |> 
  mutate(team = fct_inorder(squad)) |> relocate(team, .after="squad")
```

```{r}
current_standings_team <- current_standings |> select(squad, team)
```

```{r}
library(ggbump)
```

```{r}
df_total |> 
 # mutate(matchday = as.character(matchday),
 #        rk = as.numeric(rk)) |> 
  ggplot(aes(x = matchday, y = rk, group = squad, colour = squad)) +
  geom_line()
```

```{r}
df_total |> left_join(current_standings_team)
```

```{r}
team_colours <- tribble(~team             , ~colour,
                        "Arsenal"      	  ,"#DB0007",
                        "Bournemouth"  	  ,"#B50E12",
                        "Leeds" 	        ,"#FFCD00",
                        "Crystal Palace"	,"#1B458F",
                        "Leicester"	      ,"#003090",
                        "Man City"	      ,"#6CABDD",
                        "Newcastle"	      ,"#241F20",
                        "Spurs"	          ,"#FFFFFF",
                        "West Ham"	      ,"#7A263A",
                        "Aston Villa"	    ,"#95bfe5",
                        "Brighton"	      ,"#0057B8",
                        "Chelsea"	        ,"#034694",
                        "Everton"	        ,"#003399",
                        "Liverpool"     	,"#c8102E",
                        "Man Utd"	        ,"#DA291C",
                        "Fulham"	        ,"#000000",
                        "Southampton"	    ,"#d71920",
                        "Nottm Forest"	  ,"#e53233",
                        "Wolves"	        ,"#FDB913",
                        "Brentford"	      ,"#e30613"
)
```

```{r}
team_colours$colour
```
```{r}
current_standings_team <- current_standings_team |> left_join(team_colours, by = "team") |>  group_by(squad) |> distinct(team, .keep_all = TRUE) |> ungroup()
```

```{r}
library(ggh4x)
```


```{r}
strip <- strip_themed(background_x = elem_list_rect(fill = current_standings_team$colour.y))

```
```{r}
current_s
```


```{r}
df_total2 <- df_total |>  left_join(current_standings_team, by= "squad")
```

```{r}
df_total2
```

```{r}
df_total2
```

```{r}
df_total2 |> 
  ggplot(aes(x = matchday, y = rk, group = team, colour = team)) +
  geom_bump() + 
  scale_y_reverse() + facet_wrap2(~ team, strip = strip)# +
 # theme(strip.background = element_rect(colour = "blue", fill= "blue"))
```

```{r}
df_total3 <- df_total2 |> 
  mutate(colour = fct_reorder(colour.x, team))
```

```{r}
df_total3 |> 
  ggplot(aes(x = matchday, y = rk, group = team, colour = team)) +
  geom_bump() +
  scale_y_reverse() + facet_wrap2(~ team, strip = strip_themed(background_x = elem_list_rect(fill = df_total3$colour)))
```



```{r}
fotmob_get_league_tables(
  country = "ENG",
  league_name = "Premier League"
)
```

```{r}
data |> 
  ggplot(aes(as.character(x) = matchday, y = rk)) +
  geom_line()
```


```{r}
results_by_matchweek <- df_total |> 
  select(squad, matchday, rk) |> 
  pivot_wider(names_from = matchday, values_from = rk) 
  
```


```{r}
results_by_matchweek |> 
  ggplot(x = )
```

```{r}
data <- tm_matchday_table(country_name="England", start_year="2022", matchday=1)
```

```{r}
data
```


```{r}
unique(data, matchday)
```


```{r}
df_total
```


```{r}
df_total |> filter(matchday == 21)
```
```{r}
df_total |> select(matchday, rk, squad, pts) |> 
  filter(squad == "Man Utd") 
```

